# Generated by Django 4.2.19 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='application_status',
            field=models.CharField(choices=[('waiting', 'รอสัมภาษณ์'), ('interviewed', 'สัมภาษณ์แล้ว'), ('hired', 'รับงานแล้ว'), ('not_passed', 'ไม่ผ่าน')], default='waiting', max_length=11),
        ),
        migrations.AddField(
            model_name='person',
            name='experience',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gmail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='position_applied',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
