# Generated by Django 4.2.19 on 2025-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_person_last_name_remove_person_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='application_status',
            field=models.CharField(choices=[('waiting', 'รอสัมภาษณ์'), ('interviewed', 'สัมภาษณ์แล้ว'), ('hired', 'รับงานแล้ว'), ('not_passed', 'ไม่ผ่าน')], default='waiting', max_length=11, verbose_name='สถานะใบสมัคร (Status)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(verbose_name='ประสบการณ์ (Experience)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ (First_name)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gmail',
            field=models.EmailField(max_length=254, verbose_name='อีเมล (Gmail)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='นามสกุล (Last_name)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์ (Phone_number)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_applied',
            field=models.CharField(max_length=100, verbose_name='ตำแหน่งที่สมัคร (Position_applied)'),
        ),
    ]
